query VideoQuery(
  $filter: String
  $first: Int
  $skip: Int
  $orderBy: VideoOrderByInput
) {
  videos(filter: $filter, first: $first, skip: $skip, orderBy: $orderBy) {
    id
    mov_uuid
    cover_uuid
    mov_name
    cover_name
    name
    keyword
    description
    category {
      id
      name
    }
    owner {
      name
    }
    viewnumber
    likes
    dislikes
    isEncoded
    createdAt
  }
}
